POST http://localhost:8080/conversions HTTP/1.1
content-type: application/json

[
    {
        "id": 12,
        "loinc": "718-7",
        "unit": "g/dL",
        "value": 12
    }
]
####


POST http://localhost:8080/conversions HTTP/1.1
content-type: application/json

[
    {
        "loinc": "718-7",
        "unit": "g/dL",
        "value": 12
    },
    {
        "loinc": "59260-0",
        "unit": "mmol/l",
        "value": 10
    }
]
####



POST http://localhost:8080/conversions HTTP/1.1
content-type: application/json

[
    {
        "loinc": "59260-0",
        "unit": "mol/l"
    },
    {
        "loinc": "718-7",
        "unit": "mg/dl"
    },
    {
        "loinc": "59260-0",
        "unit": "mol/l"
    },
    {
        "loinc": "718-7",
        "unit": "mg/dl"
    },
    {
        "loinc": "59260-0",
        "unit": "mol/l"
    },
    {
        "loinc": "718-7",
        "unit": "mg/dl"
    },
    {
        "loinc": "59260-0",
        "unit": "mol/l"
    },
    {
        "loinc": "718-7",
        "unit": "mg/dl"
    },
    {
        "loinc": "59260-0",
        "unit": "mol/l"
    },
    {
        "loinc": "718-7",
        "unit": "mg/dl"
    },
    {
        "loinc": "59260-0",
        "unit": "mol/l"
    },
    {
        "loinc": "718-7",
        "unit": "mg/dl"
    },
    {
        "loinc": "59260-0",
        "unit": "mol/l"
    },
    {
        "loinc": "718-7",
        "unit": "mg/dl"
    },
    {
        "loinc": "59260-0",
        "unit": "mol/l"
    },
    {
        "loinc": "718-7",
        "unit": "mg/dl"
    },
    {
        "loinc": "59260-0",
        "unit": "mol/l"
    },
    {
        "loinc": "718-7",
        "unit": "mg/dl"
    },
    {
        "loinc": "59260-0",
        "unit": "mol/l"
    },
    {
        "loinc": "718-7",
        "unit": "mg/dl"
    },
    {
        "loinc": "59260-0",
        "unit": "mol/l"
    },
    {
        "loinc": "718-7",
        "unit": "mg/dl"
    },
    {
        "loinc": "59260-0",
        "unit": "mol/l"
    },
    {
        "loinc": "718-7",
        "unit": "mg/dl"
    },
    {
        "loinc": "59260-0",
        "unit": "mol/l"
    },
    {
        "loinc": "718-7",
        "unit": "mg/dl"
    },
    {
        "loinc": "59260-0",
        "unit": "mol/l"
    },
    {
        "loinc": "718-7",
        "unit": "mg/dl"
    },
    {
        "loinc": "59260-0",
        "unit": "mol/l"
    },
    {
        "loinc": "718-7",
        "unit": "mg/dl"
    },
    {
        "loinc": "59260-0",
        "unit": "mol/l"
    },
    {
        "loinc": "718-7",
        "unit": "mg/dl"
    },
    {
        "loinc": "59260-0",
        "unit": "mol/l"
    },
    {
        "loinc": "718-7",
        "unit": "mg/dl"
    },
    {
        "loinc": "59260-0",
        "unit": "mol/l"
    },
    {
        "loinc": "718-7",
        "unit": "mg/dl"
    },
    {
        "loinc": "59260-0",
        "unit": "mol/l"
    },
    {
        "loinc": "718-7",
        "unit": "mg/dl"
    },
    {
        "loinc": "59260-0",
        "unit": "mol/l"
    },
    {
        "loinc": "718-7",
        "unit": "mg/dl"
    },
    {
        "loinc": "59260-0",
        "unit": "mol/l"
    },
    {
        "loinc": "718-7",
        "unit": "mg/dl"
    },
    {
        "loinc": "59260-0",
        "unit": "mol/l"
    },
    {
        "loinc": "718-7",
        "unit": "mg/dl"
    }
]

{
    "loinc": "5445",
    "unit": "mg/dl",
    "factor": "gfgfsagfdws"
}