name: scheduled

on:
  repository_dispatch: {}
  workflow_dispatch: {}
  schedule:
    - cron: "00 18 * * *"

permissions: read-all

jobs:
  schedule:
    uses: miracum/.github/.github/workflows/standard-schedule.yaml@0acca4e2cf641d828c9514dce0ff70511b448cc2 # v1.5.9
    permissions:
      contents: read
      issues: write
      security-events: write
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
